services:

  nodejs:
    build:
      context: ./.docker/nodejs
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app

  rabbitmq:
    build: 
      context: ./.docker/rabbitmq
      dockerfile: Dockerfile.plugins
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin