services:

  nodejs:
    build:
      context: .docker/nodejs
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:4.1.0-management
    ports:
      - 5672:5672 # rabbitmq port
      - 15672:15672 # app management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
